# Generated by Django 5.1.3 on 2024-12-23 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0004_remove_order_product_remove_order_quantity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productsorders',
            name='quantity',
            field=models.PositiveIntegerField(),
        ),
    ]
